/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xerial_larray_impl_LArrayNative */

#ifndef _Included_xerial_larray_impl_LArrayNative
#define _Included_xerial_larray_impl_LArrayNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xerial_larray_impl_LArrayNative
 * Method:    copyToArray
 * Signature: (JLjava/lang/Object;II)I
 */
JNIEXPORT jint JNICALL Java_xerial_larray_impl_LArrayNative_copyToArray
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     xerial_larray_impl_LArrayNative
 * Method:    copyFromArray
 * Signature: (Ljava/lang/Object;IJI)I
 */
JNIEXPORT jint JNICALL Java_xerial_larray_impl_LArrayNative_copyFromArray
  (JNIEnv *, jobject, jobject, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
